//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4KursOsen1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Event
    {
        public int User_ID { get; set; }
        public int Event_ID { get; set; }
        public Nullable<bool> Is_Vinner { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
